/*
 * Copyright (c) 2026 xiayu
 * Contact: 126240622+xiayu1987@users.noreply.github.com
 * SPDX-License-Identifier: MIT
 */
import { LENGTH_THRESHOLDS } from "@noobot/shared/length-thresholds";

// --- 常量集合（避免每次调用 new Set） ---
export const MARKDOWN_EXTS = new Set(["md", "markdown", "mdx"]);
export const IMAGE_EXTS = new Set([
  "png",
  "jpg",
  "jpeg",
  "jfif",
  "pjpeg",
  "pjp",
  "gif",
  "webp",
  "bmp",
  "svg",
  "ico",
  "avif",
  "apng",
  "tif",
  "tiff",
  "heic",
  "heif",
]);
export const TEXT_PREVIEW_EXTS = new Set([
  "txt",
  "text",
  "log",
  "csv",
  "tsv",
  "json",
  "jsonl",
  "ndjson",
  "xml",
  "yaml",
  "yml",
  "toml",
  "ini",
  "conf",
  "config",
  "env",
  "properties",
  "gitignore",
  "gitattributes",
  "editorconfig",
  "npmrc",
  "yarnrc",
  "dockerignore",
  "sql",
  "graphql",
  "gql",
  "html",
  "htm",
  "css",
  "scss",
  "sass",
  "less",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "ts",
  "tsx",
  "vue",
  "svelte",
  "py",
  "rb",
  "php",
  "java",
  "c",
  "cc",
  "cpp",
  "cxx",
  "h",
  "hpp",
  "cs",
  "go",
  "rs",
  "swift",
  "kt",
  "kts",
  "scala",
  "sh",
  // cross-platform-allow: this is a file extension label, not a shell execution dependency.
  "bash",
  "zsh",
  "fish",
  "ps1",
  "bat",
  "cmd",
  "dockerfile",
  "makefile",
]);
export const OFFICE_EXTS = new Set([
  "doc",
  "docx",
  "xls",
  "xlsx",
  "ppt",
  "pptx",
  "rtf",
  "odt",
  "ods",
  "odp",
]);
export const MARKDOWN_MIMES = new Set([
  "text/markdown",
  "text/x-markdown",
  "application/markdown",
  "application/x-markdown",
]);
export const NON_IMAGE_PREVIEW_MAX_BYTES = LENGTH_THRESHOLDS.clientPreview.nonImageMaxBytes;
