/*
 * Copyright (c) 2026 xiayu
 * Contact: 126240622+xiayu1987@users.noreply.github.com
 * SPDX-License-Identifier: MIT
 */
import { TURN_COMMAND } from "@noobot/session-protocol";
import { EXECUTION_QUERY_COMMAND } from "@noobot/shared/execution-lifecycle-protocol";

export const AGENT_TRANSPORT_PROTOCOL_VERSION = 2;

export const AGENT_COMMAND = Object.freeze({
  SEND: TURN_COMMAND.SEND,
  RESEND: TURN_COMMAND.RESEND,
  CONTINUE: TURN_COMMAND.CONTINUE,
  STOP: TURN_COMMAND.STOP,
  FINALIZE: TURN_COMMAND.FINALIZE,
  TURN_SNAPSHOT_GET: TURN_COMMAND.SNAPSHOT_GET,
  EXECUTION_SNAPSHOT_GET: EXECUTION_QUERY_COMMAND.SNAPSHOT_GET,
  EXECUTION_CHILDREN_GET: EXECUTION_QUERY_COMMAND.CHILDREN_GET,
  EXECUTION_TREE_GET: EXECUTION_QUERY_COMMAND.TREE_GET,
  INTERACTION_RESPONSE: "interaction.response",
});

export const RUN_COMMAND_TYPES = Object.freeze([
  AGENT_COMMAND.SEND,
  AGENT_COMMAND.RESEND,
  AGENT_COMMAND.CONTINUE,
]);

export const EXECUTION_QUERY_COMMAND_TYPES = Object.freeze([
  AGENT_COMMAND.EXECUTION_SNAPSHOT_GET,
  AGENT_COMMAND.EXECUTION_CHILDREN_GET,
  AGENT_COMMAND.EXECUTION_TREE_GET,
]);

export const AGENT_COMMAND_TYPES = Object.freeze([
  ...RUN_COMMAND_TYPES,
  AGENT_COMMAND.STOP,
  AGENT_COMMAND.FINALIZE,
  AGENT_COMMAND.TURN_SNAPSHOT_GET,
  ...EXECUTION_QUERY_COMMAND_TYPES,
  AGENT_COMMAND.INTERACTION_RESPONSE,
]);
